export const SEND_MESSAGE = "SEND_MESSAGE";
export const UPDATE_MESSAGE_BODY = "UPDATE_MESSAGE_BODY";

export const SEND_POST = "SEND_POST";
export const UPDATE_POST_BODY = "UPDATE_POST_BODY";
export const SET_USER_PROFILE = "SET_USER_PROFILE";

export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";
export const SET_USERS = "SET_USERS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_USERS_COUNT = "SET_TOTAL_USERS_COUNT";
export const TOGGLE_IS_FETCHING = "TOGGLE_IS_FETCHING";
export const TOGGLE_IS_FOLLOWING_PROGRESS = "TOGGLE_IS_FOLLOWING_PROGRESS";

export const SET_USER_DATA = "SET_USER_DATA";
